version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /b7_24
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /m7_24
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
